#+title: NeoVim Configuration
#+author: Ranko Kohime
#+email: ranko.kohime@runbox.com
#+startup: content
#+property: header-args+ :mkdirp yes
#+property: header-args+ :tangle-mode (identity #o444)
#+property: header-args+ :comments no
#+property: header-args+ :padline no
#+property: header-args+ :tangle no

* Notes
[[https://www.notonlycode.org/neovim-lua-config/][From init.vim to init.lua - a crash course]]

Consider [[https://github.com/LazyVim/LazyVim][LazyVim]]

If using [[https://github.com/LnL7/vim-nix][vim-nix]], [[http://nicknovitski.com/vim-nix-syntax][One Magic Line of Code that fixes Nix syntax highlighting in Vim]]


* NeoVim [0/0]
:properties:
:header-args: :tangle no
:header-args+: :noweb-ref neovim-configuration
:end:

** Keymappings
  You can be more specific about when you want mappings to apply by using
  nmap, vmap, and imap. These tell Vim to only use the mapping in normal,
  visual, or insert mode respectively.
*** Preamble
**** Keymapping functions
***** map
#+begin_src lua
function map(mode, shortcut, command)
  vim.api.nvim_set_keymap(mode, shortcut, command, { noremap = true, silent = true })
end
#+end_src

***** imap
#+begin_src lua
function imap(shortcut, command)
  map('i', shortcut, command)
end
#+end_src

***** nmap
#+begin_src lua
function nmap(shortcut, command)
  map('n', shortcut, command)
end
#+end_src

***** vmap
#+begin_src lua
function vmap(shortcut, command)
  map('v', shortcut, command)
end
#+end_src

**** Set Leader key
Lazy plugin manager requires leader to be mapped before calling,
hence why Keymappings are ahead of Plugins
***** Disable Leader in normal and visual modes
#+begin_src lua
nmap('<Space>', '<Nop>')
vmap('<Space>', '<Nop>')
#+end_src

***** Set Leader key
#+begin_src lua
vim.g.mapleader = " "
#+end_src

**** Disable Ex mode keys
[[https://vi.stackexchange.com/questions/457/does-ex-mode-have-any-practical-use][Does Ex mode have any practical use?]]
See usage of Q below in Buffer handling
#+begin_src lua
nmap('n', 'q:', '<Nop>')
vmap('n', 'Q', '<Nop>')
#+end_src

*** Allow backspace in insert mode
#+begin_src lua
vim.opt.backspace = "indent,eol,start"
#+end_src

*** Delete a line with \
#+begin_src lua
nmap('\', 'dd')
#+end_src

*** Move 1 more lines up or down in normal and visual selection modes
#+begin_src lua
nmap('K', ':m .-2<CR>==')
nmap('J', ':m .+1<CR>==')
vmap('K', ':m \'<-2<CR>gv=gv')
vmap('J', ':m \'>+1<CR>gv=gv')
#+end_src

*** Fix Join line
#+begin_src lua
nmap('<leader>J', ':join<CR>')
#+end_src

*** Cut, Copy, Paste
"Normal" keybindings for Cut/Copy/Paste on desktop
Visual for Cut/Copy, Insert/Normal for pasting
#+begin_src lua
vmap('<leader>x', '"+x')
vmap('<leader>c', '"+y')
nmap('<leader>v', '"+p')
imap('<leader>v', '<C-r>+')
#+end_src

*** Saving and opening files
#+begin_src lua
nmap('<C-s>', ':w<CR>')
nmap('<leader>s', ':w<CR>')
nmap('<leader>e', ':e<space>')
#+end_src

*** Upper CASE WORD, lower case word
#+begin_src lua
nmap('<leader>u', 'gUiw')
nmap('<leader>l', 'guiw')
#+end_src

*** Quote word
#+begin_src lua
nmap('<leader>"', 'viw<ESC>a"<ESC>bi"<ESC>lel')
nmap('<leader>\'', 'viw<ESC>a\'<ESC>bi\'<ESC>lel')
#+end_src

*** Quote selected text (does not work with visual block or line)
Not sure about this one, leaving the original recipe here for now
#+begin_src lua
vmap('<leader>"', 's"<ESC>bi"<ESC>lel')
vmap('<leader>\'', 's\'<ESC>bi\'<ESC>lel')
#+end_src
   vnoremap <leader>" <esc>`<i"<esc>`>la"<esc>
   vnoremap <leader>' <esc>`<i'<esc>`>la'<esc>

*** Buffer handling
**** Close current buffer
#+begin_src lua
nmap('<leader>w', ':bd<CR>')
#+end_src
**** Next and Previous buffers on Up and Down respectively
#+begin_src lua
nmap('<leader>k', ':bn<CR>')
nmap('<leader>j', ':bp<CR>')
#+end_src
**** Select buffer from list
#+begin_src lua
nmap('<leader>b', ':buffers<CR>:buffer<space>')
#+end_src

*** Map jk as <esc> in Insert mode
#+begin_src lua
imap('jk', '<esc>')
#+end_src

*** Navigate splits using Ctrl+h/j/k/l
#+begin_src lua
nmap('<C-h>', '<C-w>h')
nmap('<C-j>', '<C-w>j')
nmap('<C-k>', '<C-w>k')
nmap('<C-l>', '<C-w>l')
#+end_src

** Plugin management with Lazy
*** Bootstrap Lazy
#+begin_src lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)
#+end_src

*** Call Lazy
#+begin_src lua
require("lazy").setup({
#+end_src

*** Plugins
**** Color schemes
***** Catppuccino
{
  "AZanellato/Catppuccino.nvim",
  lazy = true,
  priority = 1000,
  opts = {},
}
***** Monokai Pro color scheme
#+begin_src lua
{
  "loctvl842/monokai-pro.nvim",
  lazy = true,
  priority = 1000,
  opts = {},
}
#+end_src

***** Tokyo Night
#+begin_src lua
{
  "folke/tokyonight.nvim",
  lazy = true,
  priority = 1000,
  opts = {},
},
#+end_src

**** Airline status bar & themes
#+begin_src lua
"vim-airline/vim-airline",
"vim-airline/vim-airline-themes",
#+end_src

**** Leap (for fast motions)
#+begin_src lua
"ggandor/leap.nvim",
#+end_src

**** Pear Tree
Pairing for Quotations, brackets, etc...
#+begin_src lua
"tmsvg/pear-tree",
#+end_src

**** Tabular
#+begin_src lua
"godlygeek/tabular",
#+end_src

**** Treesitter
#+begin_src lua
"nvim-treesitter/nvim-treesitter",
#+end_src

**** Anyline
#+begin_src lua
{
  "huy-hng/anyline.nvim",
  dependencies = "treesitter",
},
#+end_src

**** Git
#+begin_src lua
"tpope/vim-fugitive",
#+end_src

**** Dev Icons
#+begin_src lua
"ryanoasis/vim-devicons",
#+end_src

**** Orgmode (jceb/vim-orgmode)
See dependency list at [[https://github.com/jceb/vim-orgmode/blob/master/doc/orgguide.txt][line 250]]
#+begin_src lua
{
  "jceb/vim-orgmode",
  dependencies = "vim-speeddating",
}
#+end_src

**** Orgmode (nvim-orgmode/orgmode)
#+begin_src lua
{
  "nvim-orgmode/orgmode",
  dependencies = "nvim-treesitter",
}
#+end_src

**** Hardtime
Discourage exccessive use of arrow/hjkl keys
#+begin_src lua
"takac/vim-hardtime",
#+end_src

**** Markdown
#+begin_src lua
{
  "preservim/vim-markdown",
  dependencies = "tabular",
},
#+end_src

Shortcut keys for vim-markdown:

zr: reduces fold level throughout the buffer
zR: opens all folds
zm: increases fold level throughout the buffer
zM: folds everything all the way
za: open a fold your cursor is on
zA: open a fold your cursor is on recursively
zc: close a fold your cursor is on
zC: close a fold your cursor is on recursively

**** Github Copilot
Requires external dependency Node.js

#+begin_src lua
"github/copilot.vim",
#+end_src

*** WIP
" Python
" Code formatting
Plug 'psf/black'

    " Code snippet suggestions
"Plug 'sirver/ultisnips'
"Plug 'phenomenes/ansible-snippets'

*** End call to Lazy
#+begin_src lua
})
#+end_src

** Plugin management with Plug
:properties:
:header-args+: :tangle no
:end:

*** Call Plug
    #+begin_src lua
      call plug#begin('~/.config/nvim/plugged')
    #+end_src

*** Monokai Pro Color Scheme (NeoVim)
#+begin_src lua
Plug 'loctvl842/monokai-pro.nvim'
#+end_src

*** Airline Status Bar & Themes
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

*** Animated Indentations
Plug 'huy-hng/anyline.nvim'
    " ...and it's dependency, nvim-treesitter
Plug 'nvim-treesitter/nvim-treesitter'

    " Git Wrapper
Plug 'tpope/vim-fugitive'

    " Dev Icons
Plug 'ryanoasis/vim-devicons'

    " Markdown
Plug 'godlygeek/tabular'
Plug 'preservim/vim-markdown'
        " Shortcut keys for vim-markdown:
            " zr: reduces fold level throughout the buffer
            " zR: opens all folds
            " zm: increases fold level throughout the buffer
            " zM: folds everything all the way
            " za: open a fold your cursor is on
            " zA: open a fold your cursor is on recursively
            " zc: close a fold your cursor is on
            " zC: close a fold your cursor is on recursively

    " Python
      " Code formatting
Plug 'psf/black'

    " Teach yourself the right way
      " Disable arrow keys when overused
Plug 'takac/vim-hardtime'

    " Code snippet suggestions
"Plug 'sirver/ultisnips'
"Plug 'phenomenes/ansible-snippets'

    " Pairing for Quotations, brackets, etc...
Plug 'tmsvg/pear-tree'

    " Requires Node.js, 
Plug 'github/copilot.vim'

    " Emacs Org Mode for Neovim
Plug 'nvim-orgmode/orgmode'
    " ...and it's dependency, vim-speeddating
Plug 'tpope/vim-speeddating'

*** Leap (for fast motions
#+begin_src lua
Plug 'ggandor/leap.nvim'
#+end_src

*** End Plug
All of your Plugins must be added before the following line
#+begin_src lua
call plug#end()
#+end_src

** Plugin settings
*** Airline
    " Smarter tab line
    " Automatically displays all buffers when there's only one tab open.
let g:airline#extensions#tabline#enabled = 1
    " Status bar on top
let g:airline_statusline_ontop = 1
    " Use Devicons
let g:airline_powerline_fonts = 1
    " Set Airline theme
let g:airline_theme='google_dark'

*** Enable Hardtime by default
let g:hardtime_default_on = 0

*** Pear Tree
    " Enable smart pairing with pear-tree
    " Smart pairs are disabled by default:
let g:pear_tree_smart_openers = 0
let g:pear_tree_smart_closers = 0
let g:pear_tree_smart_backspace = 0

** Visual settings
*** colorcolumn
Also highlight columns 80 and 120, for size visibility
#+begin_src lua
vim.opt.colorcolumn = "80,120"
vim.cmd('highlight ColorColumn ctermbg=red guibg=red')
#+end_src

*** colorscheme
#+begin_src lua
vim.opt.background = "dark"
-- vim.opt.colorscheme = "vim-monokai-tasty"
vim.cmd[[colorscheme tokyonight-night]]
#+end_src

*** cursorline, cursorcolumn
Highlight the cursor, so we know where it bloody is
#+begin_src lua
vim.opt.cursorline = true
vim.opt.cursorcolumn = true
#+end_src

*** noruler
It's not a real fucking ruler!
#+begin_src lua
vim.opt.noruler = true
#+end_src

*** number, relativenumber
Show line numbers on the left, relative to cursor position
#+begin_src lua
vim.opt.number = true
vim.opt.relativenumber = true
#+end_src

*** scrolloff
Move viewport with cursor plus offset
#+begin_src lua
vim.opt.scrolloff = 10
#+end_src

*** showmode
Disable, as it is superfluous with vim-airline installed
#+begin_src lua
vim.opt.showmode = false
#+end_src

*** statusline
Since we have airline-vim, we don't need the built-in statusline
#+begin_src lua
vim.opt.statusline = 0
#+end_src

** General Config
*** Enable syntax highlighting
#+begin_src lua
vim.cmd('syntax on')
#+end_src

*** TODO Toggle whether the pasting includes or excludes indents (Needs fixed)
#+begin_src lua
-- vim.o.pastetoggle = '<F2>'
#+end_src

*** Set encoding (Needed for vim-devicons)
#+begin_src lua
vim.opt.encoding = "UTF-8"
#+end_src

*** TABS TABS TABS
**** Replace tabs with spaces
#+begin_src lua
vim.opt.expandtab = true
#+end_src

**** Tabs output to spaces
#+begin_src lua
vim.opt.softtabstop = 2
#+end_src

**** Affects indenting
#+begin_src lua
  vim.opt.shiftwidth = 2
#+end_src

**** Automatically indent newlines
#+begin_src lua
  vim.opt.autoindent = true
#+end_src

**** And smarten up those tabs!
#+begin_src lua
  vim.opt.smarttab = true
#+end_src

*** Store lots of :cmdline history
#+begin_src lua
vim.opt.history = 1000
#+end_src

*** Show incomplete cmds down the bottom
#+begin_src lua
vim.opt.wildmenu = true
#+end_src

*** Reload files changed outside vim
#+begin_src lua
vim.opt.autoread = true
#+end_src

*** Disable visual mouse mode
#+begin_src lua
vim.opt.mouse = ""
#+end_src

*** Make a backup before writing files
#+begin_src lua
vim.opt.backup = true
#+end_src

*** Enable spellchecking
#+begin_src lua
vim.opt.spell = true
vim.opt.spelllang = "en"
#+end_src

*** Split behavior
#+begin_src lua
vim.opt.splitbelow = true
vim.opt.splitright = true
#+end_src

*** Search behavior
**** Highlight search terms...
#+begin_src lua
vim.opt.hlsearch = true
#+end_src

**** ...dynamically as they are typed.
#+begin_src lua
vim.opt.incsearch = true
#+end_src

**** Ignore case during /-style searches, plus...
#+begin_src lua
vim.opt.ignorecase = true
#+end_src

**** Case-sensitive searches only if capital letter in search text
#+begin_src lua
vim.opt.smartcase = true
#+end_src

*** Don't ask to save when switching buffers
#+begin_src lua
vim.opt.hidden = true
#+end_src

*** Tab completion file suffixes
Suffixes that get lower priority when doing tab completion for filenames.
These are files we are not likely to want to edit or read.
#+begin_src lua
vim.opt.suffixes = ".bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc,.png,.jpg"
#+end_src

** Abbreviations
*** Signature
#+begin_src lua :noweb-ref no
  vim.cmd [[iabbrev ssig --<cr>Ranko Kohime<cr>ranko.kohime@runbox.com
#+end_src
