# fps_limit=

# vsync=

# gl_vsync=

# custom_text_center =

legacy_layout = false

cpu_stats
cpu_temp
cpu_power
# cpu_text = "CPU"
cpu_mhz
cpu_load_change
cpu_load_value
cpu_load_color

gpu_stats
gpu_temp
gpu_core_clock
gpu_mem_clock
gpu_name
gpu_power
# gpu_text = "GPU"
# vulkan_driver
gpu_load_change
gpu_load_value
gpu_load_color

fps
# fps_sampling_period=
frametime

# arch

frame_timing
histogram

# time

# resolution

#  show_fps_limit

# custom_text

# time_format = %H:%M
# time_format = [ %T %F ]
# time_format = %X # locally formatted time, because of limited glyph range, missing characters may show as '?' (e.g. Japanese)

font_size=16
# font_scale=1.0
# font_size_text=24
# font_scale_media_player = 0.55
# no_small_font

# font_file=

# font_file_text=

# font_glyph_ranges=korean, chinese, chinese_simplified, japanese, cyrillic, thai, vietnamese, latin_ext_a, latin_ext_b

position=top-left

# core_load
# core_load_change

# io_read
# io_write
# io_stats

ram
# swap
vram

# version
# engine_version
# wine

# no_display

# offset_x=
# offset_y=

# width=
# height=
# table_columns=
# cellpadding_y=

background_alpha=0.5
# alpha=

# text_color=FFFFFF
# gpu_color=2E9762
# cpu_color=2E97CB
# vram_color=AD64C1
# ram_color=C26693
# engine_color=EB5B5B
# io_color=A491D3
# frametime_color=00FF00
# background_color=020202
# media_player_color=FFFFFF
# wine_color=732010

# media_player
# media_player_name = spotify
# media_player_order = title,artist,album

# pci_dev = 0:0a:0.0

# blacklist =

# gl_size_query = viewport

# gl_bind_framebuffer = 0

# gl_dont_flip = 1

# toggle_hud=Shift_R+F12
# toggle_fps_limit=Shift_L+F1
# toggle_logging=Shift_L+F2
# reload_cfg=Shift_L+F4
# upload_log=Shift_L+F3

# autostart_log = 1

# log_duration

# output_folder = /home/<USERNAME>/mangologs

# permit_upload=1

# benchmark_percentiles=
