save-position-on-quit

#keep-open=yes

autofit-larger=90%x90%

force-window=immediate

#osc=no

geometry=50%:50%

keepaspect=yes

fs=no

ontop=yes

video-sync=display-resample

profile=gpu-hq

vo=gpu

hwdec=auto

#gpu-context=wayland

#audio-device=alsa/default

#audio-pitch-correction=no

#audio-channels=5.1

#audio-channels=auto

volume-max=250

#slang=en

#alang=fi,en

#sub-codepage=cp1256

screenshot-format=png

screenshot-directory=~/Downloads

#user-agent="Mozilla/5.0"

cache-default=307200

cache=307200

cache-pause=no

demuxer-readahead-secs=5.0

#cache-secs=50.0

#include=/path/to/the/file/you/want/to/include

[eye-cancer]
sharpen=5
