# ============================  General Settings  =============================
# Set terminal colors
set -g default-terminal "screen-256color"

# Set parent terminal title to reflect current window in tmux session 
set -g set-titles on
set -g set-titles-string "#I:#W"

    # Start index of window/pane with 1, because we're humans, not computers
set -g base-index 1
    # Panes V
set-window-option -g pane-base-index 1

# Renumber windows automatically on close
set-option -g renumber-windows on

# Set reasonable history limit
set -g history-limit 100000

# Not sure if we want mouse support yet, so let's disable it for now
set -g mouse off
# ==============================  Color scheme  ===============================

set -g status-bg colour237
setw -g window-status-style fg=colour208
setw -g window-status-current-style fg=colour232,bg=colour244
setw -g pane-active-border-style fg=colour82,bg=colour82

# ==============================  Status line  ================================

    # Set left side of status bar
set -g status-left-length 1
set -g status-left ""

    # Set all other status bar options
set -g status-justify left
set -g monitor-activity on
set -g visual-activity on

    # Set right side of status bar
set -g status-right-length 100
#set -g status-right "#(~/.config/tmux/plugins/tmux-powerline/powerline.sh right)"
set -g status-right "#[bg=colour16] #[fg=colour40]#(~/.config/tmux/scripts/memory.sh -m)%#[fg=colour158]/#[fg=colour196]#(~/.config/tmux/scripts/memory.sh -s)% #[fg=colour226]#(~/.config/tmux/scripts/battery.sh) #[fg=colour158]#H"

# ==============================  Keymappings  ================================
    # remap prefix from 'C-b' to 'C-a'
    # As a reminder, unbind frees up C-b for other uses,
unbind C-b
    # this sets C-a as the new prefix
set-option -g prefix C-a
    # and this makes C-a send the prefix key to the embedded application (nested tmux)
bind-key C-a send-prefix

    # split panes using | and -
unbind '"'
unbind %
bind | split-window -h
bind - split-window -v

    # reload config file
bind r source-file ~/.config/tmux/tmux.conf

    # switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

    # switch panes using Vim keys, with prefix
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

    # resize panes with CAPITAL Vim keys, with prefix
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

    # Home row window selection
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

  # Byobu keybindings
    # New window
bind-key -n F2 new-window -c "#{pane_current_path}"
bind-key -n C-F2 display-panes \; split-window -h -c "#{pane_current_path}"
bind-key -n S-F2 display-panes \; split-window -v -c "#{pane_current_path}"
    # Previous window/pane
bind-key -n F3 previous-window
bind-key -n S-F3 select-pane -t :-
    # Next window/pane
bind-key -n F4 next-window
bind-key -n S-F4 select-pane -t :+
    # Disconnect, kill pane
bind-key -n F6 detach
bind-key -n C-F6 kill-pane
    # Copy mode
bind-key -n F7 copy-mode

    # Keybinds for tmux-powerline
#bind C-[ run '~/path/to/tmux-powerline/mute_powerline.sh left'
#bind C-] run '~/path/to/tmux-powerline/mute_powerline.sh right'

# ==============================  Plugins  ====================================
#set -g @plugin 'tmux-plugins/tpm'
#set -g @plugin 'erikw/tmux-powerline'

    # Call TPM (Must remain at bottom of file)
#run '~/.config/tmux/plugins/tpm/tpm'
